### PR TITLE
Release 1.3.1 

### PR DESCRIPTION
**Pull request by Danthar**
Updates to Akka 1.3.5 and NLog 4.5.0

### CODE REVIEW

**Comment by snakefoot** [comment]
@Danthar Possible to have #33 included before you publish the nuget-package ?

**Comment by snakefoot** [comment]
@ Aaronontheweb & @Danthar Possible to have #33 included before you publish the nuget-package ?

**Comment by snakefoot** [comment]
@Aaronontheweb & @Danthar Possible to have #33 included before you publish the nuget-package ?

**Comment by Danthar** [comment]
@snakefoot no, pushing to master == automagical release to nuget, So it would go into the next release

**Comment by snakefoot** [comment]
No nuget package has been published for 8 months on nuget


Sent from my Samsung device


-------- Original message --------

**Pull request merged**
