### PR TITLE
Dependency update for Akka 1.3.17 and NLog 4.5.11 with NetCore3 support

### PR DESCRIPTION
**Pull request by snakefoot**
"Last" 1.3 release before ver. 1.4 with netstandard2 arrives.

### CODE REVIEW

**Comment by snakefoot** [comment]
@Danthar Possible to have this merged to `dev` and `master` with nuget-release ?

**Comment by Danthar** [comment]
Not sure. But I think we don't have ci fixed for this repo yet.

**Comment by Danthar** [comment]
I might have some time this friday. Else it will be next week. If you don't see anything  happening by next Tuesday pls remind me 😉

**Comment by snakefoot** [comment]
Hopefully it will be a quick copy/paste job from a project with working ci.

**Comment by Danthar** [comment]
Pipelines are configured and are working. But i haven't configured the project yet. See https://github.com/AkkaNetContrib/Akka.Logger.NLog/issues/45

**Pull request merged**
