### PR TITLE
NLog 4.5 supports Message Template Syntax (Unit Test)

### PR DESCRIPTION
**Pull request by snakefoot**
Confirms #36 is working

### CODE REVIEW

**Comment by snakefoot** [comment]
@Danthar I guess something has to be changed in the TeamCity configuration to exercise the unit-tests

**Comment by snakefoot** [comment]
@Danthar Anything missing for this to be merged?

**Comment by Danthar** [comment]
Nothing much. Just me finding the time to look it over. :)

**Comment by Danthar** [comment]
Oh. I just now noticed you reference akka 1.3.8 in the test project. Would you mind doing a PR to update the main project to akka 1.3.8 as well ? Then ill push a release afterwards.

**Comment by snakefoot** [comment]
@Danthar Created PR #39

**Pull request merged**
